Update tokens.json
eoscafe/eos-airdrops pull request #253
Opened 2020-10-07 11:59 UTC by niche500

## How to add token?

- [ ] Add metadata to [`tokens.json`](tokens.json)

```json
    {
    "name": "NOAM",
    "logo": "http://noam.finance/img/noam_logo.png",
    "logo_lg": "http://noam.finance/img/noam_logo.png",
    "symbol": "NOAM",
    "account": "NoamToken",
    "chain": "eos"
    },

```

- [ ] Add token logo `*.png` to [`./logos`](./logos) folder
- [ ] Update `README.md` with **Symbol** & **Contract Name**

2020-10-07 12:12 UTC, niche500 commented
Add files via upload

2020-10-07 12:13 UTC, niche500 reviewed
How to add files via upload

2020-10-07 12:30 UTC, niche500 commented
![noam_logo](https://user-images.githubusercontent.com/70435255/95330604-6fa12f00-08b1-11eb-8cad-da348e2ff79b.png)

2020-10-10 22:46 UTC, DenisCarriere commented
![image](https://user-images.githubusercontent.com/550895/95666554-c06e8d00-0b28-11eb-9da3-2a3f6453246c.png)

You must add your logo file to the repo and the `tokens.json` url must reference this local repo

2020-10-10 22:47 UTC, DenisCarriere requested changes
- [ ] add logo file
- [ ] update `tokens.json` to local repo

2020-10-16 15:41 UTC, niche500 reviewed
added the file

2020-10-17 17:53 UTC, DenisCarriere requested changes

2020-10-17 17:53 UTC, DenisCarriere commented on tokens.json
> +        "account": "NoamToken",
@niche500 this is not a valid EOS account name

Please provide a valid token contract name

2020-10-19 14:40 UTC, DenisCarriere commented
@niche500 You can re-submit once you have a valid token contract name

2020-10-19 14:40 UTC, closed without merging