Update tokens.json
eoscafe/eos-airdrops pull request #310
Opened 2021-03-04 07:47 UTC by achinta3

## How to add token?

- [ ] Add metadata to [`tokens.json`](tokens.json)

```json
{
    "name": "Rewalty",
    "logo": "https://raw.githubusercontent.com/achinta3/LOGO/main/COIN.png",
    "logo_lg": "https://raw.githubusercontent.com/achinta3/LOGO/main/COIN.png",
    "symbol": "REWA",
    "account": "wepevt3petjr",
    "chain": "eos"
}
```

- [ ] Add token logo `*.png` to [`./logos`](./logos) folder
- [ ] Update `README.md` with **Symbol** & **Contract Name**

2021-03-04 07:49 UTC, achinta3 commented
Please Add token information.

2021-03-15 21:42 UTC, DenisCarriere requested changes
the COIN.png file is empty

2021-03-15 21:43 UTC, DenisCarriere requested changes

2021-03-15 21:43 UTC, DenisCarriere commented on tokens.json
> +        "logo_lg": "https://raw.githubusercontent.com/achinta3/LOGO/main/COIN.png",
Must provide internal GitHub repo URL

2021-03-25 22:36 UTC, closed without merging

2021-03-31 11:09 UTC, achinta3 commented on tokens.json
> +        "logo_lg": "https://raw.githubusercontent.com/achinta3/LOGO/main/COIN.png",
ok