Add token from Factories World
eoscafe/eos-airdrops pull request #546
Opened 2022-10-04 14:47 UTC by Harko999

## How to add token?

- [ ] Add metadata to [`tokens.json`](tokens.json)

```json
{
    "name": "<NAME>",
    "logo": "https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/<SYMBOL>.png",
    "logo_lg": "https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/<SYMBOL>.png",
    "symbol": "<SYMBOL>",
    "account": "<CONTRACT NAME>",
    "chain": "eos"
}
```

- [ ] Add token logo `*.png` to [`./logos`](./logos) folder

2022-10-04 17:23 UTC, DenisCarriere requested changes
Logo URL should be local repo 

view others as reference

2022-10-05 11:03 UTC, Harko999 commented
https://github.com/Harko999/eos-airdrops/blob/master/logos/FAWE.png
https://github.com/Harko999/eos-airdrops/blob/master/logos/FAWG.png
https://github.com/Harko999/eos-airdrops/blob/master/logos/FAWO.png
https://github.com/Harko999/eos-airdrops/blob/master/logos/FAWS.png

вт, 4 окт. 2022 г. в 21:23, Denis ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Logo URL should be local repo
>
> view others as reference
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eoscafe/eos-airdrops/pull/546#pullrequestreview-1130351445>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3NOB2X37BQB46MEGIMQTBLWBRRZVANCNFSM6AAAAAAQ4U2DWQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-05 11:33 UTC, DenisCarriere commented
Please follow the other logo URLs and update PR

2022-10-07 12:12 UTC, closed without merging

2023-01-28 06:27 UTC, Harko999 commented
Hi eoscafe/eos-airdrops,

I'm using a new tool called Signal that helps founders find the right Investors and helps Investors attract the right deals. A lot of what powers that is who you're connected to. If we connect, it'll help both of us manage our Investor contacts better.

Please confirm our connection: http://signalmail-tracking.nfx.com/ls/click?upn=ojRnCyOQslQVr-2FL3NgSUpZzxrdEAcoYAHVA34eZvZ-2B9oymYhW-2FSKEOsgQMYroBlWsGyQI9FlHkJRrJkJ-2FRLXh97Qj76DLT7Mf-2Fswaygb1v7lx6IESXd5vNv8F65EebunofM32pzFFzyq-2FzTZFHuSDhuyUUJSSqY3VPyDFIAGJyk1ZbtiDyefcglfcfv-2F-2BL-2FCdOE-2BQcgOB5jrwHjJ17SGDuURJH0rPeNclf5wGgqAqIz07l1C7FwVITpAqb5dxs6n85CqGEjikVmg1HpGoBlmAQ-3D-3DerJG_U31jt5HgHBh7k3Grc5s4l1CEFlZSHXOaK9ED5KrmiFCa4tWKKpw9-2F1QhumEEoP-2FPylMgHWkOO9wY9gkTaSCs33xqf30-2Bzyhelt8fViWhE2Hss-2Bg59UPcNqK4-2BnHVJve0Y4LFfUhLEPjEjxUl-2BD2BNxGcBfVOLC0uOqsHCYgYzaqN-2Fj87D6ld3up-2BmoST9EUi3yjfX2KY-2FYdPjMXwb9FSohWD4XmL1IE-2FNb7PbLOhdns-2BI-2F-2BdB579b5R3D-2BrcNmFaAK2CUGjBzh3w6Hbu3rZiuOTGaTK-2Bf0f5ucE25gUpSwsbGMLbJUVmuEIx938sGCk5

Best,
Maksim